version: '3.7'

services:
  frontend:
    tty: true
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./web:/app
  backend:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    volumes:
      - ./server/src:/app/src
